spring:
  application:
    name: coder-test-backend
  datasource:
    driver-class-name: # <todo> ???
    url: # <todo> url ?????
    username: root
    password: 123456
server:
  port: 8123
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    # MyBatis ??
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # ????
      logic-delete-field: isDelete
# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      # ????????????
      packages-to-scan: com.yupi.codertestbackend.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn